Sprint 1/step 2
antcek/ReactBurgerProject pull request #3
Opened 2023-01-03 23:40 UTC by antcek

2023-01-04 07:17 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- Не все пропы компонентов типизированы
- Вынесите модальное окно и логику его отображения из `App.jsx`
- Вынесите типизацию ингредиента в отдельный файл
- Используйте isRequired для каждого поля ингредиента

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- Типизировали все поля ингредиента
- Сделали отписку от слушателя событий

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-01-04 07:17 UTC, andryxxa93 commented on src/components/app/app.jsx
> +                console.log(err)
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2023-01-04 07:17 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        const getData = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-01-04 07:17 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +BurgerConstructor.propTypes = {
**Необходимо исправить**
Необходимо вынести типизацию ингредиента в отдельный файл и экспортить оттуда куда нужно. Иначе сейчас выходит много дубликатов кода. Так же необходимо использовать isRequired для каждого поля ингредиента.

2023-01-04 07:17 UTC, andryxxa93 commented on src/components/burger-ingredients-card/burger-ingredients-card.jsx
> +function IngredientCard(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-01-04 07:17 UTC, andryxxa93 commented on src/components/app/app.jsx
> +    };
**Необходимо исправить**
Модальное окно, как и функцию открытия и закрытие модального окна лучше вынести туда где оно используется. В `BurgerIngredients ` и `BurgerConstructor`. В будущем вариантов использования модалки станет больше и тогда будет значительно сложнее ею управлять если оставить так.

2023-01-04 07:17 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +                {props.products.map((ingredient) => {
**Можно лучше**
Тут удобнее будет если вы просто как и с булкой отфильтруете ингредиенты в отдельную переменную. Логику и представление лучше отделять от друг друга - так удобнее вносить изменения и дебажить.

2023-01-04 07:17 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.jsx
> +                {props.products.map((product) => {
**Можно лучше**
Лучше передавать не айдишник ингредиента и список ингредиентов, а только сам ингредиент - так придется делать меньше операций

2023-01-04 07:17 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +Modal.propTypes = {
**Необходимо исправить**
Тут не хватает пропа `children`

2023-01-04 07:17 UTC, andryxxa93 commented on src/utils/data.js
> +export const ingredients = [
**Можно лучше**
Этот файл больше не нужен, его можно удалить

2023-01-04 12:19 UTC, antcek commented on src/utils/data.js
> +export const ingredients = [
удален

2023-01-04 12:48 UTC, antcek commented on src/components/app/app.jsx
> +                console.log(err)
добавил состояние error, сообщение при ошибке выводится на экран

2023-01-04 13:39 UTC, antcek commented on src/components/app/app.jsx
> +        const getData = async () => {
вынес в отдельную функцию

2023-01-04 14:06 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +BurgerConstructor.propTypes = {
сделал

2023-01-04 14:29 UTC, antcek commented on src/components/burger-ingredients-card/burger-ingredients-card.jsx
> +function IngredientCard(props) {
исправил везде

2023-01-04 14:31 UTC, antcek commented on src/components/modal/modal.jsx
> +Modal.propTypes = {
добавлен

2023-01-04 14:47 UTC, antcek commented on src/components/app/app.jsx
> +    };
вынес модал с функционалом в конструктор и ингредиентс

2023-01-04 15:07 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +                {props.products.map((ingredient) => {
добавил фильтрацию в отдельную константу

2023-01-04 15:20 UTC, antcek commented on src/components/ingredient-details/ingredient-details.jsx
> +                {props.products.map((product) => {
вынес отдельно константу

2023-01-04 17:04 UTC, antcek commented on src/components/ingredient-details/ingredient-details.jsx
> +                {props.products.map((product) => {
исправил насколько интеллект позволяет

2023-01-05 19:10 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-01-05 20:32 UTC, merged