Sprint 2/step 2
antcek/ReactBurgerProject pull request #5
Opened 2023-01-22 01:05 UTC by antcek

2023-01-22 05:14 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;

### **Но есть несколько  замечаний, которые нужно исправить:**

- В запросе `/orders` у вас идёт дублирование ингредиентов, <https://disk.yandex.com/i/xQ25GPAOK7XqVQ>;

- Перенесите thunk-actions (выши запросы к апи) в папку services.

### **Сделает код лучше:**

- При клике на таб плавно скролить список ингредиентов к нужному разделу;

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-01-22 05:14 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [priceCount, priceCountDispatcher] = useReducer(priceReducer, initialPriceCount);
**Можно лучше:**

Рекомендую не использовать context или redux, для подсчёта цены. Лучше используете useMemo)

2023-01-22 05:14 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +        let currentTarget = event.currentTarget;
**Можно лучше:**

**здесь и далее в других местах** если переменная не перезаписывается её нужно объявлять как `const`, это помогает понять другим разработчикам, как мы будем использовать переменную, будем ли мы в коде перезаписывать её значение.
Так же стоит помнить, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а только изменяют его внутренне состояние и такие переменные так же объявляются как const

2023-01-22 05:14 UTC, ArslanMustafin commented on src/components/burger-constructor-ingredients/burger-constructor-ingredients.jsx
> +export default function DraggedIngredientCard({ onOpenModal, ingredient, index, id, moveIngredient }) {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2023-01-22 05:14 UTC, ArslanMustafin commented on src/components/burger-constructor-ingredients/burger-constructor-ingredients.jsx
> +                <div  style={{cursor:'pointer'}}   >
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-01-22 05:14 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
>                  <div style={{ display: 'flex' }}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-01-22 05:14 UTC, ArslanMustafin commented on src/components/burger-constructor-ingredients/burger-constructor-ingredients.jsx
> +                        type={undefined}
**Можно лучше:**

Можно просто не передавать пропс)

2023-01-22 05:14 UTC, ArslanMustafin commented on src/utils/burger-api.js
> +        const apiIngredients = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить**
вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2023-01-22 05:14 UTC, ArslanMustafin commented on src/utils/burger-api.js
> +            const response = await fetch(apiIngredients);
**Можно лучше:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше  разместить их в отдельном файле  `utils/burger-api.js`

Например:

```js

const NORMA_API = `https://norma.nomoreparties.space/api`;

export function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(checkResponse)
}

export function sendOrder(data) {
   return fetch(`${NORMA_API}/orders`)
    .then(checkReponse )
}

```

проверка ответа сервера и преобразование из json дублируется в нескольких местах, нужно вынести в отдельную функцию:

```js
const checkResponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-01-22 05:14 UTC, ArslanMustafin commented on src/utils/burger-api.js
> +        const idConstructor = { ingredients: Array.from(idNodeElements).map(ingredient => ingredient.id) };
**Надо исправить:**

Вы должны передавать ингредиенты в функцию через параметр, а генерировать ингредиенты в самом компоненте `burger-constructor`

2023-01-22 05:14 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                            <DragIcon />
**Можно лучше:**

Мне кажется лучше выглядить будет, если этой иконки не будет))

2023-01-22 05:14 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                            key={index}
**Можно лучше:**

Лучше не использовать index в качестве значения key. https://stackoverflow.com/questions/46735483/error-do-not-use-array-index-in-keys)
Если будете исправлять, то генерировать уникальное значение лучше в action-creator, при добавлении ингредиента.

2023-01-22 05:14 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    }, [constructorIngredients])
**Надо исправить:**

В этом методе должны быть условия, для того, чтобы диспатч срабатывал только после того как элемент изменит свою позицию. Сейчас он срабатывает постоянно, если мы как-то двигаем элемент (но при этом он не меняет своего места).

2023-01-22 12:36 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [priceCount, priceCountDispatcher] = useReducer(priceReducer, initialPriceCount);
вроде как useReducer это хук реакта, по тз написано что на юсРедьюсере стоит написать

2023-01-22 12:39 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +        let currentTarget = event.currentTarget;
исправил

2023-01-22 12:53 UTC, antcek commented on src/components/burger-constructor-ingredients/burger-constructor-ingredients.jsx
> +export default function DraggedIngredientCard({ onOpenModal, ingredient, index, id, moveIngredient }) {
описал

2023-01-22 12:55 UTC, antcek commented on src/components/burger-constructor-ingredients/burger-constructor-ingredients.jsx
> +                <div  style={{cursor:'pointer'}}   >
убрал инлайн

2023-01-22 12:59 UTC, antcek commented on src/components/burger-ingredients/burger-ingredients.jsx
>                  <div style={{ display: 'flex' }}>
убрал

2023-01-22 13:00 UTC, antcek commented on src/components/burger-constructor-ingredients/burger-constructor-ingredients.jsx
> +                        type={undefined}
сделано

2023-01-22 13:04 UTC, antcek commented on src/utils/burger-api.js
> +        const apiIngredients = 'https://norma.nomoreparties.space/api/ingredients';
cделал

2023-01-22 13:22 UTC, antcek commented on src/utils/burger-api.js
> +        const idConstructor = { ingredients: Array.from(idNodeElements).map(ingredient => ingredient.id) };
перенёс в компонент orderDetails, т.к в конструкторе выбрасывается undefined

2023-01-22 13:56 UTC, antcek commented on src/utils/burger-api.js
> +            const response = await fetch(apiIngredients);
сделал

2023-01-22 13:58 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +                            <DragIcon />
да, но по макету надо))

2023-01-22 14:06 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +                            key={index}
сделал с помощью генерации ключа в экшне (наставница сказала ок)

2023-01-22 14:24 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +    }, [constructorIngredients])
исправил

2023-01-22 23:41 UTC, antcek commented
оставил некоторые закомментированные участки кода, не сделал нормально стилизацию у dnd, тк планирую это чуть позже через доп. библиотеки

2023-01-23 12:43 UTC, merged

2023-01-24 04:49 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [priceCount, priceCountDispatcher] = useReducer(priceReducer, initialPriceCount);
Да действительно, в теории рекомендуют использовать useReducer) но именно тут оптимальным вариантом будет подсчёт стоимости в самом компоненте, с использованием useMemo))

2023-01-24 04:54 UTC, ArslanDev666 commented on src/utils/burger-api.js
> +        const idConstructor = { ingredients: Array.from(idNodeElements).map(ingredient => ingredient.id) };
Делать запрос лучше в компоненте burger-costructor, а сам запрос/сервис оставить в burger-api))
Компонент `order-details` не подходит для запроса, т.к. он отвечает за контент модального окна, и не должен знать (и делать) ничего, кроме номера заказа))

2023-01-24 04:56 UTC, ArslanDev666 commented
> оставил некоторые закомментированные участки кода, не сделал нормально стилизацию у dnd, тк планирую это чуть позже через доп. библиотеки

Немного не понял про стилизацию, но ладно))

2023-01-24 04:57 UTC, ArslanDev666 commented
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работ принята, удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены;

2023-01-24 13:27 UTC, antcek commented
> > оставил некоторые закомментированные участки кода, не сделал нормально стилизацию у dnd, тк планирую это чуть позже через доп. библиотеки
> 
> Немного не понял про стилизацию, но ладно))

имел в виду визуал при переносе)