Sprint 3/step 1
antcek/ReactBurgerProject pull request #6
Opened 2023-02-04 00:06 UTC by antcek

2023-02-04 04:27 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно запретить пользователю отправлять заказ, если он не выбрал булки и ингредиенты: <https://disk.yandex.com/i/vB9gVysObCLCKA>;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/ouTVegu-HUzDQw>;

- В хедер запроса POST `/orders` нужно передавать токен `Authorization: Bearer ...`;

- Вы должны отслеживать onSubmit событие формы, а не клик по кнопке);

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-04 04:27 UTC, ArslanMustafin commented on src/pages/login/login.jsx
> +        } htmlType="button" type="primary" size="large">
**Надо исправить:**

Вы должны отслеживать `onSubmit` событие формы, а не клик по кнопке)
Ну и тип у кнопки будет submit.

2023-02-04 04:27 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +                        }
**Можно лучше:**

Весь неиспользуемый код, лучше удалить.

2023-02-04 04:27 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +                        }
**Надо исправить:**

Здесь и далее.

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили. 

И className лучше написать так: 

```js
className={({isActive}) => classNames(styles.element, { 'text_color_inactive': !isActive })}
```

2023-02-04 04:27 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    }, [])
**Можно лучше:**

Немного не понимаю, а зачем именно в `burger-constructor` делать это?

2023-02-04 04:27 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
>      const draggedIngredientsPrice = constructorIngredients.reduce((accum, curr) => accum + curr.price, 0);
**Можно лучше:**

Лучше делать это в useMemo (когда вы считаете totalPrice).

2023-02-04 04:27 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    )
**Можно лучше:**

Лучше написать вот так:

```js
const burgerAllId = useMemo(() => {
  return { ingredients: [bunsForOrder[0],...constructorIngredients,bunsForOrder[0]].map(ingredient => ingredient._id) }
}, [burgerForOrder])
```

Я бы ещё немного поменял `bunsForOrder`, сделал бы просто объект, а не массив, т.к. мы точно знаем что булки будут одинаковы.

2023-02-04 04:27 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                    </div>}
**Надо исправить:**

Здесь не должно быть условий, лучше обрабатывать условия в обработчике событий (в отдельной функции).

2023-02-04 04:27 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                    : <OrderDetails onCloseModal={onCloseModal} />}
**Можно лучше:**

Лучше разместить попап с `IngredientDetails`, в компоненте `burger-ingredients`, т.к. именно с этим компонентом связан попап)

2023-02-04 04:27 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
>      const sauce = products.filter(ingredient => ingredient.type === 'sauce');
**Можно лучше:**

Лучше обернуть в useMemo)

2023-02-04 04:27 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const containerRef = document.getElementById('ingredients-container');
**Надо исправить:**

Вы ведь уже делаете логику через useRef. Старайтесь делать всё в едином стиле.

2023-02-04 04:27 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                    duration={400}
**Надо исправить**

Здесь и далее.

вынесите магическое значение 400 в именованную константу.

2023-02-04 04:27 UTC, ArslanDev666 commented on src/pages/profile/profile.jsx
> +  const [passwordValue, setPasswordValue] = useState('');
**Можно лучше**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-02-04 15:03 UTC, antcek commented on src/pages/login/login.jsx
> +        } htmlType="button" type="primary" size="large">
сделал

2023-02-04 15:36 UTC, antcek commented on src/components/app-header/app-header.jsx
> +                        }
исправил

2023-02-04 15:38 UTC, antcek commented on src/components/app-header/app-header.jsx
> +                        }
удалил

2023-02-04 19:18 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +    }, [])
поменял логику, убрал

2023-02-04 19:42 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +    )
сделал

2023-02-04 19:44 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
>      const draggedIngredientsPrice = constructorIngredients.reduce((accum, curr) => accum + curr.price, 0);
сделал

2023-02-04 19:45 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +                    : <OrderDetails onCloseModal={onCloseModal} />}
сделал

2023-02-04 21:23 UTC, antcek commented on src/components/burger-constructor/burger-constructor.jsx
> +                    </div>}
вынес в отдельную функцию

2023-02-04 21:30 UTC, antcek commented on src/components/burger-ingredients/burger-ingredients.jsx
>      const sauce = products.filter(ingredient => ingredient.type === 'sauce');
обернул

2023-02-04 21:34 UTC, antcek commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const containerRef = document.getElementById('ingredients-container');
подправил

2023-02-04 21:35 UTC, antcek commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                    duration={400}
вынес

2023-02-04 22:49 UTC, antcek commented on src/pages/profile/profile.jsx
> +  const [passwordValue, setPasswordValue] = useState('');
в профиле добавил

2023-02-04 23:41 UTC, antcek commented
По поводу дизейбла кнопки с возможностью сделать заказ - она выключена только если нет булок, по тз и со слов наставницы клиент может сделать заказ, имея только булки в конструкторе

2023-02-05 08:11 UTC, ArslanDev666 commented
> По поводу дизейбла кнопки с возможностью сделать заказ - она выключена только

Окей) немного не логично правда, но пусть будет так))

2023-02-05 08:15 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Все замечания были исправлены;

2023-02-05 14:17 UTC, merged