Sprint 4/step 1
antcek/ReactBurgerProject pull request #7
Opened 2023-02-20 12:40 UTC by antcek

пока не дошли до типизации редакса - вышло достаточно много as any и any типов

2023-02-20 15:12 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Проект теперь типизирован;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно у всех обработчиков событий, которые отмечены в коде, и у которых `event:any`, поставить нужный тип, `KeyboardEvent, MouseEvent и т.д ...`;

- Типы для пропсов лучше класть рядом с компонентом, не нужно их куда-то выносить))

### **Сделает код лучше:**

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-02-20 15:12 UTC, ArslanMustafin commented on src/utils/api.ts
> +export const API_UPDATE_USER_INFO: string = 'https://norma.nomoreparties.space/api';
**Можно лучше:**

Тут не стоит указывать тип явно.

Typesript сам определяет литеральные типы)) а константы при typeof дают своё значение.

2023-02-20 15:12 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
>          return { ...constructorBuns }
**Можно лучше:**

Не совсем понимаю, зачем тут снова делать объект, почему сразу нельзя вернуть `constructorBuns`.

2023-02-20 15:12 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
>      const totalPrice = useMemo(() => {
**Надо исправить:**

Тут лучше явно указать, что возвращается число.

```js
const totalPrice = useMemo<number>(() => {...}, [])
```

2023-02-20 15:12 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
> +    function onOpenModal(event: any): void {
**Надо исправить:**

Тут должен быть тип события мыши: `React.MouseEvent<HTMLDivElement>`.

Первую возникнувшую ошибку можно исправить вот так: `(event.target as HTMLElement).closest`, а вот со второй, вам придётся поменять немного логику.

2023-02-20 15:12 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.tsx
> +    function onOpenModal(event: any): void {
**Надо исправить:**

Здесь вы тоже должны поставить тип.

2023-02-20 15:12 UTC, ArslanDev666 commented on src/components/modal/modal.tsx
> +import {IModal} from '../../services/types/types';
**Надо исправить:**

Типы лучше класть рядом с компонентом, не нужно их куда-то выносить))

2023-02-20 15:12 UTC, ArslanDev666 commented on src/components/modal/modal.tsx
> +        function modalEscClose(event: any): void {
**Надо исправить:**

Тут должен быть тип `KeyboardEvent`

2023-02-20 15:12 UTC, ArslanDev666 commented on src/pages/forgot-password/forgot-password.tsx
> +  const onLoginForgot = (e: any) => {
**Надо исправить:**

Тут тип у события должен быть - `ChangeEvent<HTMLInputElement>`

2023-02-20 15:12 UTC, ArslanDev666 commented on src/pages/forgot-password/forgot-password.tsx
> +  const handleSubmitRecover = (event: any) => {
**Надо исправить:**

Тип у события должен быть `FormEvent`

2023-02-20 15:12 UTC, ArslanDev666 commented on src/pages/login/login.tsx
> +  const onLoginChange = (e: any) => {
**Надо исправить:**

Здесь и далее.

Исправьте типы по аналогии с `ForgotPasswordPage`.

2023-02-20 15:12 UTC, ArslanDev666 commented on src/pages/register/register.tsx
> +  const onLoginRegister = (e: any): void => setLoginValue(e.target.value);
**Надо исправить:**

Здесь и далее.

Исправьте типы по аналогии с `ForgotPasswordPage`.

2023-02-20 15:12 UTC, ArslanDev666 commented on src/pages/reset-password/reset-password.tsx
> +  const onPasswordChange = (e: any): void => {
**Надо исправить:**

Здесь и далее.

Исправьте типы по аналогии с `ForgotPasswordPage`.

2023-02-20 15:12 UTC, ArslanDev666 commented on src/services/custom-hooks/custom-hooks.tsx
> +    handleChange: (event: any) => void;
**Надо исправить:**

Вы должны указывать тип событию.

2023-02-20 15:12 UTC, ArslanDev666 commented on src/services/types/types.ts
> +  onOpenModal: (event?: any) => void;
**Надо исправить:**

Вы должны указать тип событию.

2023-02-21 12:44 UTC, antcek commented on src/utils/api.ts
> +export const API_UPDATE_USER_INFO: string = 'https://norma.nomoreparties.space/api';
принял

2023-02-21 12:49 UTC, antcek commented on src/components/burger-constructor/burger-constructor.tsx
>          return { ...constructorBuns }
вернул

2023-02-21 12:53 UTC, antcek commented on src/components/burger-constructor/burger-constructor.tsx
>      const totalPrice = useMemo(() => {
указал

2023-02-21 13:20 UTC, antcek commented on src/components/burger-constructor/burger-constructor.tsx
> +    function onOpenModal(event: any): void {
исправил

2023-02-21 13:21 UTC, antcek commented on src/components/burger-ingredients/burger-ingredients.tsx
> +    function onOpenModal(event: any): void {
исправил

2023-02-21 13:34 UTC, antcek commented on src/components/modal/modal.tsx
> +import {IModal} from '../../services/types/types';
переделал

2023-02-21 13:37 UTC, antcek commented on src/components/modal/modal.tsx
> +        function modalEscClose(event: any): void {
сделал

2023-02-21 13:38 UTC, antcek commented on src/pages/forgot-password/forgot-password.tsx
> +  const onLoginForgot = (e: any) => {
сделал

2023-02-21 13:41 UTC, antcek commented on src/pages/forgot-password/forgot-password.tsx
> +  const handleSubmitRecover = (event: any) => {
+

2023-02-21 13:42 UTC, antcek commented on src/pages/login/login.tsx
> +  const onLoginChange = (e: any) => {
исправил

2023-02-21 13:43 UTC, antcek commented on src/pages/register/register.tsx
> +  const onLoginRegister = (e: any): void => setLoginValue(e.target.value);
исправил

2023-02-21 13:43 UTC, antcek commented on src/pages/reset-password/reset-password.tsx
> +  const onPasswordChange = (e: any): void => {
+

2023-02-21 13:44 UTC, antcek commented on src/services/custom-hooks/custom-hooks.tsx
> +    handleChange: (event: any) => void;
указал

2023-02-21 13:47 UTC, antcek commented on src/services/types/types.ts
> +  onOpenModal: (event?: any) => void;
указал

2023-02-21 17:55 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-02-21 17:56 UTC, merged