Sprint 5/step 1
antcek/ReactBurgerProject pull request #8
Opened 2023-03-07 20:00 UTC by antcek

2023-03-08 06:17 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 

Что понравилось:
- Сокеты открываютс и закрываются согласно тех заданию
- Раздельное хранение данных полученных с сокета
- Отличная типизация хранилища
- Созданы отдельные экшены для данных юзера и общих данных


Что необходимо исправить:
- Если открыть какой-то заказ, то можно увидеть, что булок в нем - 4 штуки, что конечно невозможно. Скорее всего дело в том, что при оформлении заказа вы дважды указываете id булок, хотя достаточно один раз. 
<img width="827" alt="Снимок экрана 2023-03-08 в 09 00 22" src="https://user-images.githubusercontent.com/60173362/223631898-430c57ad-faf2-49c7-85f5-28c88860fc9b.png">
<img width="1440" alt="Снимок экрана 2023-03-08 в 09 02 45" src="https://user-images.githubusercontent.com/60173362/223632187-583621a5-3485-4b96-89c3-d9d16482a57b.png">

- Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message` 'Invalid or missing token'` то его необходимо обновить через `refreshToken`.

**Можно лучше**
- У вас в хранилище в `wsReducer` есть два объекта - `messages` и `userOrders.` Что такое `userOrders` сразу понятно, но вот, что такое `messages` не сразу понимаешь, лучше называть конкретно. Например `allOrders`.
 <img width="481" alt="Снимок экрана 2023-03-08 в 09 07 58" src="https://user-images.githubusercontent.com/60173362/223632997-79e1f5d3-f44b-4f6b-ae17-330010d1a7b0.png">
- Если во время отправки данных с форм происходит ошибка, то её лучше показывать пользователю, например текстом под формой, чтобы он понимал, что происходит.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-08 06:17 UTC, andryxxa93 commented on src/components/app/app.tsx
> +    const productsFailed = useSelector((store) => store.getProducts.productsFailed);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-08 06:17 UTC, andryxxa93 commented on src/services/middleware/socketMiddleware.ts
> +        socket.onmessage = (event) => {
**Необходимо исправить**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message `'Invalid or missing token' `то его необходимо обновить через `refreshToken`.

2023-03-08 15:13 UTC, antcek commented on src/components/app/app.tsx
> +    const productsFailed = useSelector((store) => store.getProducts.productsFailed);
сделал в указанном компоненте, остальное оформлю позже при рефакторинге общем

2023-03-08 15:13 UTC, antcek commented on src/services/middleware/socketMiddleware.ts
> +        socket.onmessage = (event) => {
сделал

2023-03-09 06:47 UTC, andryxxa93 requested changes
- Не работает обновление токена при получении истории заказов. У вас уже есть функция обновления токена, нужно использовать её. Так же следует добавить таймер, чтобы код обновления не срабатывал два раза - иначе выпадет ошибка. Воспроизвести ошибку можно так - зайти в профиль, поменять в куках accesToken (достаточно один символ заменить) и перейти в "Историю заказов". 
Выглядеть это должно примерно так -
```
if (parsedData.message === 'Invalid or missing token') {
              const { accessToken } = await updateToken();
             ...
            }
```

<img width="1439" alt="Снимок экрана 2023-03-09 в 09 25 58" src="https://user-images.githubusercontent.com/60173362/223939214-ae43a843-9459-45ec-aaf5-1a5732372b62.png">

- В модалке с информацией о заказе необходимо считать все повторяющиеся ингредиенты и увеличивать их счетчик и цену. Пожалуйста посмотрите как в фигме.

2023-03-13 19:30 UTC, antcek commented
По поводу подсчёта ингредиентов - есть проблема в виде того, что с сервера автоматические заказы приходят с 1 булкой(когда должны 2), но наставница говорила что булки считать стоит всегда как две, так что если в ленте появляются иногда заказы с одной иконкой булки, подсчёт идёт в любом случае как за 2, при заказе, сделанном от руки всегда появляются
по 2 булки, как и должно быть. 
По сокетам  старшим ревьюером одобрено вроде как

2023-03-14 06:44 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-15 12:18 UTC, merged